<?php

namespace TS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluatorRepository extends EntityRepository
{
    public function getAllEvaluators() {
        $query = $this->createQueryBuilder('e')
                ->getQuery();
        return $query->getResult();
    }
}
