<?php

namespace TS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExcelQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcelQuestionRepository extends EntityRepository
{
    
    
    public function getExcelQuestions() {
        $query = $this->createQueryBuilder('t')
                 ->orderBy('t.name', 'asc')
                ->getQuery();
        return $query->getResult();
    }
    
    public function getStringIdExcelQuestions($ids) {
        $query = $this->createQueryBuilder('q')
                ->where("q.id IN(:ids)")
                ->setParameter('ids', $ids)
                ->getQuery();
        return $query->getResult();
    }
    
    public function getExcelQuestionsById($id) {
        $query = $this->createQueryBuilder('q')
                 ->where("q.id IN(:id)")
                ->setParameter('id', $id)
                ->getQuery();
        return $query->getResult();
    }
}
