<?php

namespace TS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends EntityRepository {

    public function invitedCandidates($username) {
        $query = $this->createQueryBuilder('i')
                ->join('i.evaluators', 'e', 'WITH', 'e.username= :username')
                ->setParameter('username', $username)
                ->join('i.candidates', 'c', 'WITH', 'c.status IS NOT NULL')
                ->addSelect('c');
        return $query->getQuery()->getResult();
    }

    public function invitationTrace($id, $date, $date1) {
        $query = $this->createQueryBuilder('i')
                ->Where('i.dateCreation = :date')
                ->orWhere('i.dateCreation = :date1')
                ->setParameter('date', $date)
                ->setParameter('date1', $date1)
                ->join('i.candidates', 'c', 'WITH', 'c.id = :id')
                ->setParameter('id', $id);
        return $query->getQuery()->getResult();
    }

}
