<?php

namespace TS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends EntityRepository
{

     public function getStatus() {
        $query = $this->createQueryBuilder('s')
                ->getQuery();
        return $query->getResult();
    }
}
