<?php

namespace TS\LDAPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TS_adminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TSadminRepository extends EntityRepository {

    public function getCandidates() {
        $query = $this->createQueryBuilder('u')
                ->where('u.role= :role')
                ->setParameter('role', "candidate")
                ->orderBy('u.username', 'asc')
                ->getQuery();
        return $query->getResult();
    }

    public function getRHs() {
        $query = $this->createQueryBuilder('u')
                ->where('u.role= :role')
                ->setParameter('role', "RH")
                ->orderBy('u.username', 'asc')
                ->getQuery();
        return $query->getResult();
    }

    public function getAdmins() {
        $query = $this->createQueryBuilder('u')
                ->where('u.role= :role')
                ->setParameter('role', "admin")
                ->orderBy('u.username', 'asc')
                ->getQuery();
        return $query->getResult();
    }

}
