<?php

namespace TS\CandidatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CandidatResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatResponseRepository extends EntityRepository
{
}
