<?php

namespace TS\CandidatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CandidatTestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatTestsRepository extends EntityRepository {

    public function testTrace($id, $date) {
//        echo $date;
        $query = $this->createQueryBuilder('t')
                ->Where('t.date = :date')
                ->setParameter('date', $date)
                ->join('t.candidates', 'c', 'WITH', 'c.id = :id')
                ->setParameter('id', $id);
        return $query->getQuery()->getResult();
    }

    public function getFreeResponses($id) {
        $note = "need correction";
        $query = $this->createQueryBuilder('t')
                ->Where('t.id = :id')
                ->setParameter('id', $id)
                ->join('t.responses', 'r', 'WITH', 'r.note = :note')
                ->setParameter('note', $note);
        return $query->getQuery()->getResult();
    }

    public function getDecision($name) {
        $query = $this->createQueryBuilder('ct')
                 ->Where('ct.name = :name')
                ->setParameter('name', $name);
        return $query->getQuery()->getResult();
    }
    
     public function getCandidatTests($idTest) {
        $query = $this->createQueryBuilder('ct')
                 ->Where('ct.testId = :id')
                ->setParameter('id', $idTest);
        return $query->getQuery()->getResult();
    }
    
    
}
