parameters:
#    ts_candidat.example.class: TS\CandidatBundle\Example

services:
#    ts_candidat.example:
#        class: %ts_candidat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
